name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Waka Readme Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          BLOCKS: ░▒▓█
          SHOW_TIME: true
          SHOW_TITLE: true
          SECTION_NAME: waka
          SHOW_MASKED_TIME: true
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
